name: gcp_secret_manager
description: A small package to make interacting with Google Secret Manager easier.
version: 0.0.1
homepage: https://github.com/Morel-Tech/gcp_secret_manager

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  current_gcp_project: ^0.0.1
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.2
