name: gcp_secret_manager
description: A small package to make interacting with Google Secret Manager easier.
version: 0.1.4
homepage: https://github.com/Morel-Tech/gcp_secret_manager

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  current_gcp_project: ^0.0.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.3.1
  http: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
